# Generated by Django 4.1 on 2024-08-26 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_set_cate'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='test',
            name='escape_rate',
            field=models.CharField(default=0.2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='state',
            field=models.CharField(default='starting', max_length=50),
        ),
        migrations.AlterField(
            model_name='set',
            name='cate',
            field=models.CharField(default='事实测试', max_length=50),
        ),
    ]
