# Generated by Django 4.1 on 2024-08-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_set_created_at_test_created_at_test_escape_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='suite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.suite'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='set',
            name='cate',
            field=models.CharField(default='jailbreak', max_length=50),
        ),
    ]
